[package]
version = "1.0.0"
category = "Simulation"
title = "Nolon Sim Samples"
description = "Scenarios extensions for Isaac Sim"
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.examples.browser" = {}
"isaacsim.examples.extension" = {}
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "nolon_scenarios_python.move_ur5"

[[python.module]]
name = "nolon_scenarios_python.limo_diff"

args = [
    "--enable",
]
